todo_manager/todo_list/urls.py
from django.urls import path, include
from . import views

app_name = "todo_list"

urlpatterns = [
    path('', views.ToDoListIndexView.as_view(), name="index"),
    path('<int:pk>/', views.ToDoDetailView.as_view(), name="detail"),
    path('list/', views.ToDoListView.as_view(), name="list"),
    path('done/', views.ToDoListDoneView.as_view(), name="done"),
]

todo_manager/todo_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name='index.html'), name="index"),
    path('todos/', include('todo_list.urls')),
    path('admin/', admin.site.urls),
]

todo_manager/todo_list/models.py
from django.db import models

# Create your models here.
class ToDoItem(models.Model):

    class Meta:
        ordering = ("id", )
        verbose_name = "ToDo Item"

    title = models.CharField(max_length=250)
    done = models.BooleanField(default=False)


    def __str__(self):
        return self.title

todo_manager/todo_list/views.py
from django.shortcuts import render
from django.http import (
    HttpRequest,
    HttpResponse,
)
from django.views.generic import TemplateView, ListView, DetailView

from .models import ToDoItem

def index_view(request: HttpRequest) -> HttpResponse:
    todo_items = ToDoItem.objects.all()[:3]
    return render(
        request,
        template_name="todo_list/index.html",
        context={"todo_items":todo_items},
    )

class ToDoListIndexView(ListView):
    template_name = "todo_list/index.html"
    queryset = ToDoItem.objects.all()[:3]

class ToDoListView(ListView):
    model = ToDoItem

class ToDoListDoneView(ListView):
    queryset = ToDoItem.objects.filter(done=True).all()


class ToDoDetailView(DetailView):
    model = ToDoItem

todo_manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>
    {% block title %}
      Base Title
    {% endblock title %}
  </title>
</head>
<body>
  {% include "components/navbar.html" %}
  {% block body %}
    Base Body!
  {% endblock body %}
<footer>
  &copy; Django TODO App
  {% block footer %}
  {% endblock %}
</footer>
</body>
</html>

todo_manager/templates/components/navbar.html
<nav>
  <ul>
    <li><a href="{% url 'index' %}">Home</a></li>
    <li><a href="{% url 'todo_list:index' %}">ToDo List</a></li>
    <li><a href="#">About</a></li>
  </ul>
</nav>

todo_manager/templates/index.html
{% extends 'base.html' %}

{% block title %}
  TODO App Index
{% endblock title %}

{% block body %}
  <h1>Welcome to our TODO App!</h1>
  <h2>Welcome to our TODO App!</h2>
  <h3>It is {% now "jS F Y" %}</h3>
{% endblock body %}

todo_manager/todo_list/templates/todo_list/base.html
{% extends 'base.html' %}

{% block footer %}
  ToDo List
{% endblock %}

todo_manager/todo_list/templates/todo_list/components/todo_items_list.html
<ul>
  {% for todo_item in object_list %}
  <li>
    <a href= "{% url 'todo_list:detail' pk=todo_item.pk %}" >
      {{ todo_item.title }}
      {% if todo_item.done %}
        ✅
      {% else %}
        ❌
      {% endif %}
    </a>
  </li>
  {% endfor %}
</ul>

todo_manager/todo_list/templates/todo_list/index.html
{% extends 'index.html' %}

{% block title %}
  ToDO List App
{% endblock %}

{% block body %}
  <h1>ToDo List App</h1>
  <div>
    <li><a href="{% url 'todo_list:list' %}">All ToDo Items</a></li>
    <li><a href="{% url 'todo_list:done' %}">Done todo items</a></li>
  </div>
  <h2>ToDos:</h2>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_detail.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDO #{{ object.pk }}
{% endblock %}

{% block body %}
  <h3>ToDo:</h3>
  <div>
    <div>Title: <strong>{{ object.title  }}</strong></div>
    <div>Done: <strong>{{ object.done  }}</strong></div>
  </div>
{% endblock %}

todo_manager/todo_list/templates/todo_list/todoitem_list.html
{% extends 'todo_list/base.html' %}

{% block title %}
  ToDO List
{% endblock %}

{% block body %}
  <h3>ToDos:</h3>
  {% include 'todo_list/components/todo_items_list.html' %}
{% endblock %}